<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="6" total="9" passed="0" failed="3" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-05-05T17:11:14 IST" name="Suite" finished-at="2022-05-05T17:13:31 IST" duration-ms="136294">
    <groups>
    </groups>
    <test started-at="2022-05-05T17:11:14 IST" name="Test" finished-at="2022-05-05T17:13:31 IST" duration-ms="136294">
      <class name="com.VTiger.TestCases.TC_03WithTestNG">
        <test-method is-config="true" signature="launchBrowser()[pri:0, instance:com.VTiger.TestCases.TC_03WithTestNG@771a660]" started-at="2022-05-05T17:12:23 IST" name="launchBrowser" finished-at="2022-05-05T17:12:28 IST" duration-ms="4374" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method is-config="true" signature="login()[pri:0, instance:com.VTiger.TestCases.TC_03WithTestNG@771a660]" started-at="2022-05-05T17:12:28 IST" name="login" finished-at="2022-05-05T17:12:31 IST" duration-ms="3388" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method signature="createcontact_org()[pri:0, instance:com.VTiger.TestCases.TC_03WithTestNG@771a660]" started-at="2022-05-05T17:12:31 IST" name="createcontact_org" finished-at="2022-05-05T17:13:16 IST" duration-ms="45306" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertFalse(Assert.java:67)
at org.testng.Assert.assertFalse(Assert.java:77)
at com.VTiger.TestCases.TC_03WithTestNG.createcontact_org(TC_03WithTestNG.java:75)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createcontact_org -->
        <test-method is-config="true" signature="logout()[pri:0, instance:com.VTiger.TestCases.TC_03WithTestNG@771a660]" started-at="2022-05-05T17:13:16 IST" name="logout" finished-at="2022-05-05T17:13:19 IST" duration-ms="2908" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
      </class> <!-- com.VTiger.TestCases.TC_03WithTestNG -->
      <class name="com.VTiger.TestCases.TC_02WithTestNG">
        <test-method is-config="true" signature="connecttoDB()[pri:0, instance:com.VTiger.TestCases.TC_02WithTestNG@7d4f9aae]" started-at="2022-05-05T17:11:14 IST" name="connecttoDB" finished-at="2022-05-05T17:11:14 IST" duration-ms="5" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- connecttoDB -->
        <test-method is-config="true" signature="launchBrowser()[pri:0, instance:com.VTiger.TestCases.TC_02WithTestNG@7d4f9aae]" started-at="2022-05-05T17:11:14 IST" name="launchBrowser" finished-at="2022-05-05T17:11:22 IST" duration-ms="7355" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method is-config="true" signature="login()[pri:0, instance:com.VTiger.TestCases.TC_02WithTestNG@7d4f9aae]" started-at="2022-05-05T17:11:22 IST" name="login" finished-at="2022-05-05T17:11:25 IST" duration-ms="3572" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method signature="createorg_dd()[pri:0, instance:com.VTiger.TestCases.TC_02WithTestNG@7d4f9aae]" started-at="2022-05-05T17:11:25 IST" name="createorg_dd" finished-at="2022-05-05T17:11:47 IST" duration-ms="21475" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertFalse(Assert.java:67)
at org.testng.Assert.assertFalse(Assert.java:77)
at com.VTiger.TestCases.TC_02WithTestNG.createorg_dd(TC_02WithTestNG.java:57)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createorg_dd -->
        <test-method is-config="true" signature="logout()[pri:0, instance:com.VTiger.TestCases.TC_02WithTestNG@7d4f9aae]" started-at="2022-05-05T17:11:47 IST" name="logout" finished-at="2022-05-05T17:11:50 IST" duration-ms="3036" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:com.VTiger.TestCases.TC_02WithTestNG@7d4f9aae]" started-at="2022-05-05T17:13:19 IST" name="closeBrowser" finished-at="2022-05-05T17:13:31 IST" duration-ms="11441" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method is-config="true" signature="disConnectDB()[pri:0, instance:com.VTiger.TestCases.TC_02WithTestNG@7d4f9aae]" started-at="2022-05-05T17:13:31 IST" name="disConnectDB" finished-at="2022-05-05T17:13:31 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- disConnectDB -->
      </class> <!-- com.VTiger.TestCases.TC_02WithTestNG -->
      <class name="com.VTiger.TestCases.TC_01WithTestNG">
        <test-method is-config="true" signature="launchBrowser()[pri:0, instance:com.VTiger.TestCases.TC_01WithTestNG@73e9cf30]" started-at="2022-05-05T17:11:50 IST" name="launchBrowser" finished-at="2022-05-05T17:11:54 IST" duration-ms="4272" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method is-config="true" signature="login()[pri:0, instance:com.VTiger.TestCases.TC_01WithTestNG@73e9cf30]" started-at="2022-05-05T17:11:54 IST" name="login" finished-at="2022-05-05T17:11:58 IST" duration-ms="3641" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method signature="createorg()[pri:0, instance:com.VTiger.TestCases.TC_01WithTestNG@73e9cf30]" started-at="2022-05-05T17:11:58 IST" name="createorg" finished-at="2022-05-05T17:12:20 IST" duration-ms="22124" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertFalse(Assert.java:67)
at org.testng.Assert.assertFalse(Assert.java:77)
at com.VTiger.TestCases.TC_01WithTestNG.createorg(TC_01WithTestNG.java:51)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createorg -->
        <test-method is-config="true" signature="logout()[pri:0, instance:com.VTiger.TestCases.TC_01WithTestNG@73e9cf30]" started-at="2022-05-05T17:12:20 IST" name="logout" finished-at="2022-05-05T17:12:23 IST" duration-ms="2914" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
      </class> <!-- com.VTiger.TestCases.TC_01WithTestNG -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
